dataset:
  name: sparse_estep_lc_nusc
  superpixel: data/nuscenes/seeds_1024
  sparse_label_path: data/nuscenes/weak_label_4

model:
  imagenet_pretrain: pretrain/resnet18-5c106cde.pth
  in_channel: 4
  proj_channel: 256
  is_estep: True
  name: spvcnn_swiftnet18_nusc_assop2p
  cr: 0.64
