criterion:
  name: lc_lovasz
  ignore_index: 0

dataset:
  name: lc_semantic_nusc

model:
  imagenet_pretrain: pretrain/resnet18-5c106cde.pth
  build_image_decoder: True
  in_channel: 4
  proj_channel: 256
  name: spvcnn_swiftnet18_nusc
  cr: 0.64